# This file can be used with kubectl create -f to import it into Kubernetes. 
# Also useable with Podman kube play -f to create a pod from this file.
#
# Created with podman-5.8.2
apiVersion: v1
kind: ConfigMap
metadata:
  name: js-app-config
data:
  ME_CONFIG_BASICAUTH_ENABLED: "true"

---

apiVersion: v1
kind: Secret
metadata:
  name: js-app-secret
data:
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4= # base64 encoded value of "admin"
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQ= # base64 encoded value of "password"
  ME_CONFIG_MONGODB_URL: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkQDEyNy4wLjAuMTo3MjAxNy8= # base64 encoded value of "mongodb://admin:password@127.0.0.1:27017/"
  ME_CONFIG_BASICAUTH_ENABLED: dHJ1ZQ== # base64 encoded value of "true"
  ME_CONFIG_BASICAUTH_USERNAME: bW9uZ3VzZXI= # base64 encoded value of "mongouser"
  ME_CONFIG_BASICAUTH_PASSWORD: bW9uZ3VzZXJwYXNz # base64 encoded value of "mongouserpass"
  
---

apiVersion: v1
kind: Pod
metadata:
  labels:
    app: js-app
  name: js-app
spec:
  restartPolicy: Always
  containers:
    - name: frontend
      image: localhost/js-app:latest
      env:
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              name: js-app-secret
              key: ME_CONFIG_MONGODB_URL     
      ports:
        - containerPort: 3000
          hostPort: 3000
      args:
        - node
        - server.js
    - name: mongo-server
      image: docker.io/library/mongo:latest
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: js-app-secret
              key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: js-app-secret
              key: MONGO_INITDB_ROOT_PASSWORD

    - name: mongo-express
      image: docker.io/mongo-express:latest
      ports:
        - containerPort: 8081
          hostPort: 18081
      env:
        - name: ME_CONFIG_MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: js-app-secret
              key: ME_CONFIG_MONGODB_URL
        - name: ME_CONFIG_BASICAUTH_ENABLED
          valueFrom:
            configMapKeyRef:
              name: js-app-config
              key: ME_CONFIG_BASICAUTH_ENABLED
        - name: ME_CONFIG_BASICAUTH_USERNAME
          valueFrom:
            secretKeyRef:
              name: js-app-secret
              key: ME_CONFIG_BASICAUTH_USERNAME
        - name: ME_CONFIG_BASICAUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: js-app-secret
              key: ME_CONFIG_BASICAUTH_PASSWORD

